# https://supabase.com/docs/guides/cli/config

[functions.evolution-admin]
verify_jwt = true

[functions.notify-ticket-whatsapp]
verify_jwt = true

[functions.sharepoint-treinamentos]
verify_jwt = true

[functions.orquestrai-treinamento]
verify_jwt = true

[functions.notify-stale-tickets]
verify_jwt = true

[functions.sioe-evidencia-callback]
verify_jwt = true

[functions.official-photos]
verify_jwt = true
